# Generated by Django 2.2.1 on 2019-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
