# Generated by Django 2.2.1 on 2019-06-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20190604_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('in', 'in'), ('not_in', 'not in')], max_length=10)),
                ('source', models.CharField(choices=[('feed', 'Feed'), ('title', 'Title'), ('body', 'Body'), ('link', 'Link'), ('tag', 'Tags')], max_length=10)),
                ('action', models.CharField(choices=[('hide', 'Hide Article'), ('show', 'Show Article')], max_length=10)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds')),
            ],
        ),
    ]
