# Generated by Django 2.2.1 on 2019-06-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_filters_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
