# Generated by Django 2.2.1 on 2019-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20190606_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='keyword',
            field=models.CharField(max_length=30),
        ),
    ]
