# Generated by Django 2.2.1 on 2019-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20190606_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='filters',
            name='keyword',
            field=models.CharField(max_length=30),
        ),
    ]
