# Generated by Django 2.2.2 on 2019-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20190609_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
