# Generated by Django 2.2.1 on 2019-06-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20190609_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds')),
            ],
            options={
                'unique_together': {('tag', 'feed')},
            },
        ),
    ]
