# Generated by Django 2.2.1 on 2019-06-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20190610_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='found',
            field=models.IntegerField(default=1),
        ),
    ]
