# Generated by Django 2.2.1 on 2019-06-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_tags_found'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
