# Generated by Django 2.2.2 on 2019-06-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20190610_1654'),
        ('feeds', '0015_delete_tags'),
    ]

    operations = [
    ]
