# Generated by Django 2.2.2 on 2019-06-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_merge_20190611_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('full_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='feeds',
            name='full_text',
            field=models.BooleanField(default=False),
        ),
    ]
