# Generated by Django 2.2.2 on 2019-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_auto_20190611_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullarticles',
            old_name='full_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='fullarticles',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
