# Generated by Django 2.2.2 on 2019-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_auto_20190612_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
