# Generated by Django 2.2.1 on 2019-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_feeds_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullarticles',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds'),
            preserve_default=False,
        ),
    ]
