# Generated by Django 2.2.1 on 2019-06-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_fullarticles_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='full_text',
        ),
    ]
