# Generated by Django 2.2.1 on 2019-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_remove_feeds_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='folder',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
