# Generated by Django 2.2.1 on 2019-06-17 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_feeds_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('date_hidden', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 22, 54, 52, 63801))),
                ('active_hidden_filters_ul', models.TextField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds')),
            ],
        ),
    ]
