# Generated by Django 2.2.1 on 2019-06-17 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0026_auto_20190617_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenarticles',
            name='date_hidden',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 22, 56, 23, 910461, tzinfo=utc)),
        ),
    ]
