# Generated by Django 2.2.1 on 2019-06-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0029_auto_20190617_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenarticles',
            name='date_hidden',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
