# Generated by Django 2.2.1 on 2019-06-18 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0031_auto_20190618_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullarticles',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
