# Generated by Django 2.2.1 on 2019-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0032_fullarticles_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='remove_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='stop_html',
            field=models.TextField(blank=True),
        ),
    ]
