# Generated by Django 2.2.1 on 2019-06-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0033_auto_20190620_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=250)),
                ('ignore', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds')),
            ],
        ),
    ]
