# Generated by Django 2.2.1 on 2019-06-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0034_feedvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='report_hidden_articles',
            field=models.BooleanField(default=True),
        ),
    ]
