# Generated by Django 2.2.1 on 2019-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0035_feeds_report_hidden_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='remove_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='stop_html',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
