# Generated by Django 2.2.1 on 2019-07-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0037_auto_20190626_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('full_article', models.BooleanField(default=False)),
                ('full_article_retries', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('hidden_date', models.DateTimeField(blank=True)),
                ('hidden_active_keywords', models.TextField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feeds')),
                ('scraper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feeds.ArticleScrapers')),
            ],
        ),
    ]
