# Generated by Django 2.2.1 on 2019-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0038_articlerecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecords',
            name='pub_date',
            field=models.CharField(max_length=50),
        ),
    ]
