# Generated by Django 2.2.1 on 2019-07-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0039_auto_20190701_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecords',
            name='hidden_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
