# Generated by Django 2.2.1 on 2019-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0040_auto_20190701_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecords',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlerecords',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
