# Generated by Django 2.2.1 on 2019-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0041_auto_20190701_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecords',
            name='hidden_active_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
