# Generated by Django 2.2.3 on 2019-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0043_auto_20190703_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
    ]
