version: "3.9"

x-logging: &v_logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "4"

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file:
      - ./fullfeedfilter/.env
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - LOG_FILE=false #optional
    # volumes:
    #   - /path/to/appdata/config:/config #optional
    restart: unless-stopped

  fullfeedfilter:
    container_name: fullfeedfilter
    build:
      context: .
      # context: https://github.com/martokk/fullfeedfilter.git#main
    restart: unless-stopped
    depends_on:
      - duckdns
    env_file:
      # - /home/ubuntu/volumes/fullfeedfilter/.env
      - ./fullfeedfilter/.env
    volumes:
      # - /home/ubuntu/volumes/fullfeedfilter/.env:/fullfeedfilter/.env
      # - /home/ubuntu/volumes/fullfeedfilter/media:/fullfeedfilter/media
      # - /home/ubuntu/volumes/fullfeedfilter/logs:/fullfeedfilter/logs
      # - /home/ubuntu/volumes/fullfeedfilter/db.sqlite3:/fullfeedfilter/db.sqlite3
      - ./fullfeedfilter:/fullfeedfilter
    ports:
      - "8002:8002"
